title: Sohesh's blog
description: Few Stupid Things

github:
  is_project_page: false
  is_user_page: true
  owner_name: Sohesh
  owner_url: https://soheshts.github.io/blog
  owner_gravatar_url: https://soheshts.github.io/images/me.jpg
  url: "https://soheshts.github.io"
  baseurl: "/blog"

remote_theme: soheshts/cayman
