title: Sohesh's blog
url: https://soheshts.github.io/blog
website: https://soheshts.github.io
basewebsite: /blog
repository: soheshts/blog
description: Few Stupid Things
github:
  is_project_page: false
  is_user_page: true
  owner_name: Sohesh
  owner_url: https://soheshts.github.io/
  owner_gravatar_url: https://soheshts.github.io/images/me.jpg
remote_theme: soheshts/cayman
baseurl: /blog
permalink: date
